### PR TITLE
User Delegation SAS

### LINKED ISSUE #19372: Signature did not match - SAS token is incorrectly signed
### Bug Report

- import path of package in question
```
"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/sas"
"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/service"
```
- SDK version:
 ``` github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v0.5.0```
- output of `go version`
```go version go1.19.2 darwin/amd64```

- What happened?
SAS token is incorrectly signed! I've tried different variations of this, including changing the version like suggested [here](https://github.com/Azure/azure-sdk-for-go/issues/18777), but to no avail. 
- What did you expect or want to happen?
SAS token is correctly signed
- How can we reproduce it?
```
package main

import (
	"time"
	"context"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/sas"
	"github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/service"
)

var (
	TenantID = "TenantIDXXX"
	ClientID = "ClientIDXXX"
	ClientSecret = "ClientSecretXXX"
	StorageAccount = "AccountXXX"
	Container = "ContainerXXX"
)

func main() {
	cred, err := azidentity.NewClientSecretCredential(
		TenantID,
		ClientID,
		ClientSecret,
		nil,
	)
	
	if err != nil {
		panic(err)
	}

	client, err := service.NewClient(
		fmt.Sprintf("https://%s.blob.core.windows.net/", StorageAccount),
		cred,
		&service.ClientOptions{},
	)
	if err != nil {
		panic(err)
	}

	now := time.Now().UTC().Add(-10 * time.Second)
	expiry := now.Add(48 * time.Hour)
	info := service.KeyInfo{
		Start:  to.Ptr(now.UTC().Format(sas.TimeFormat)),
		Expiry: to.Ptr(expiry.UTC().Format(sas.TimeFormat)),
	}

	udc, err := client.GetUserDelegationCredential(context.Background(), info, nil)
	if err != nil {
		panic(err)
	}

	values, err := sas.BlobSignatureValues{
		Protocol:      sas.ProtocolHTTPS,
		StartTime:     time.Now().UTC().Add(-10 * time.Second),
		ExpiryTime:    time.Now().UTC().Add(15 * time.Minute),
		Permissions:   to.Ptr(sas.ContainerPermissions{ Read: true }).String(),
		ContainerName: Container,
	}.SignWithUserDelegation(udc)

	if err != nil {
		panic(err)
	}
	
	token := values.Encode()

	// test the SAS token
	accountURL := fmt.Sprintf("https://%s.blob.core.windows.net?%s", StorageAccount, token)
        aClient, err := azblob.NewClientWithNoCredential(accountURL, nil)

	pager := aClient.NewListBlobsFlatPager(Container, nil)
	res, err := pager.NextPage(context.TODO())
	if err != nil {
		panic(err)
	}
}
```

which outputs:
```
panic: GET https://AccountXXX.blob.core.windows.net/ContainerXXX
--------------------------------------------------------------------------------
RESPONSE 403: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
ERROR CODE: AuthenticationFailed
--------------------------------------------------------------------------------
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:557ea56c-001e-0035-6bf6-e198a4000000
Time:2022-10-17T07:02:19.7935860Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was r
2022-10-17T07:02:09Z
2022-10-17T07:17:19Z
/blob/AccountXXX/ContainerXXX
xxx
TenantIDXXX
2022-10-17T07:02:08Z
2022-10-19T07:02:08Z
b
2020-10-02

https
2019-12-12
c





</AuthenticationErrorDetail></Error>
--------------------------------------------------------------------------------


goroutine 1 [running]:
main.main()
        /Users/xxx/repo/test.go:77 +0x885
exit status 2
```

### PR DESCRIPTION
**Pull request by souravgupta-msft**
Corrected signing of User Delegation SAS. Fixes #19372 and #19454

- [x] The purpose of this PR is explained in this or a referenced issue.
- [x] The PR does not update generated files.
   - These files are managed by the codegen framework at [Azure/autorest.go][].
- [x] Tests are included and/or updated for code changes.
- [x] Updates to [CHANGELOG.md][] are included.
- [x] MIT license headers are included in each file.

[Azure/autorest.go]: https://github.com/Azure/autorest.go
[CHANGELOG.md]: https://github.com/Azure/azure-sdk-for-go/blob/main/CHANGELOG.md

### CODE REVIEW

File: sdk/storage/azblob/sas/service.go [hunk 1]
```diff
@@ -16,28 +16,29 @@ import (
...
+	ContainerName        string
+	BlobName             string // Use "" to create a Container SAS
+	Directory            string // Not nil for a directory SAS (ie sr=d)
+	CacheControl         string // rscc
+	ContentDisposition   string // rscd
+	ContentEncoding      string // rsce
+	ContentLanguage      string // rscl
+	ContentType          string // rsct
+	BlobVersion          string // sr=bv
+	AuthorizedObjectId   string // saoid
```
Comment (jhendrixMSFT) [inline sdk/storage/azblob/sas/service.go:39]: `Id` should be all caps (see also the next line).

File: sdk/storage/azblob/sas/account.go [hunk 2]
```diff
@@ -90,71 +90,6 @@ func (v AccountSignatureValues) SignWithSharedKey(sharedKeyCredential *SharedKey
 	return p, nil
 }
 
-// SignWithUserDelegation uses an account's UserDelegationKey to sign this signature values to produce the proper SAS query parameters.
-func (v AccountSignatureValues) SignWithUserDelegation(userDelegationCredential *UserDelegationCredential) (QueryParameters, error) {
```
Comment (jhendrixMSFT) [inline sdk/storage/azblob/sas/account.go:94]: Was this removed because user delegation can't be used on the account?

File: sdk/storage/azblob/service/examples_test.go [hunk 3]
```diff
@@ -288,6 +288,8 @@ func Example_service_Client_NewClientWithUserDelegationCredential() {
 	if !ok {
 		panic("AZURE_STORAGE_ACCOUNT_NAME could not be found")
 	}
+	containerName := "testContainer"
```
Comment (jhendrixMSFT) [inline sdk/storage/azblob/service/examples_test.go:291]: Nit, looks like this should be a `const`

File: sdk/storage/azblob/sas/account.go (hunk 2 above)
Comment (souravgupta-msft) [reply sdk/storage/azblob/sas/account.go:94]: Yes, user delegation SAS can't be used for account level operations. Please refer the below link.
https://learn.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas#specify-permissions

File: sdk/storage/azblob/sas/service.go (hunk 1 above)
Comment (souravgupta-msft) [reply sdk/storage/azblob/sas/service.go]: Done

File: sdk/storage/azblob/service/examples_test.go (hunk 3 above)
Comment (souravgupta-msft) [reply sdk/storage/azblob/service/examples_test.go]: Done

**Review by jhendrixMSFT — APPROVED** [review]

**Review by siminsavani-msft — APPROVED** [review]

**Review by vibhansa-msft — APPROVED** [review]
