### PR TITLE
[azservicebus] Do a sleep in our azidentity test if it initially reports that we don't have Send claims

### LINKED ISSUE #19609: azservicebus: intermittent CBS authentication failure
Hit during live testing some updated `go-amqp` bits.  The error is inconsistent, and it's possible this is due to the updated `go-amqp` bits.  Unable to repro locally.

```
2022-11-22T18:00:41.8114564Z === RUN   TestNewClientWithAzureIdentity
2022-11-22T18:00:41.8129868Z Env cred works, being added to our chained token credential    client_test.go:61: 
2022-11-22T18:00:41.8132122Z         	Error Trace:	client_test.go:61
2022-11-22T18:00:41.8133765Z         	Error:      	Received unexpected error:
2022-11-22T18:00:41.8142253Z         	            	*Error{Condition: amqp:unauthorized-access, Description: Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb://***/queue-1729f9d8a51c505e'. TrackingId:63d119632fc045ae9c7391d7f7f671c9_G1, SystemTracker:gateway7, Timestamp:2022-11-22T17:57:27, Info: map[]}
2022-11-22T18:00:41.8144893Z         	Test:       	TestNewClientWithAzureIdentity
2022-11-22T18:00:41.8146827Z --- FAIL: TestNewClientWithAzureIdentity (2.14s)
```

### PR DESCRIPTION
**Pull request by richardpark-msft**
Adding in a workaround for the annoying "send claims" bug that manifests in CI. 

Fixes #19609

### CODE REVIEW

File: sdk/messaging/azservicebus/client_test.go [hunk 1]
```diff
@@ -58,6 +59,21 @@ func TestNewClientWithAzureIdentity(t *testing.T) {
 	require.NoError(t, err)
 
 	err = sender.SendMessage(context.TODO(), &Message{Body: []byte("hello - authenticating with a TokenCredential")}, nil)
+
+	if err != nil {
+		if strings.Contains(err.Error(), "'Send' claim(s) are required to perform this operation") {
```
Comment (jhendrixMSFT) [inline sdk/messaging/azservicebus/client_test.go:64]: Nit, you could combine this into one `if` clause to reduce indentation.

**Review by jhendrixMSFT — APPROVED** [review]

File: sdk/messaging/azservicebus/client_test.go (hunk 1 above)
Comment (richardpark-msft) [reply sdk/messaging/azservicebus/client_test.go]: Done.
