### PR TITLE
[Tables] Fix ClientOptions struct

### LINKED ISSUE #15582: [Tables] Fix ClientOptions
Rename `PerCallOptions` => `PerCallPolicies`
Add a `PerTryPolicies` option

### PR DESCRIPTION
**Pull request by seankane-msft**
closes #15582

### CODE REVIEW

**Review by RickWinter — APPROVED** [review]

File: sdk/data/aztables/zc_client_options.go [hunk 1]
```diff
@@ -11,12 +11,18 @@ import (
...
+
 	// Retry configures the built-in retry policy behavior.
 	Retry policy.RetryOptions
+
 	// Telemetry configures the built-in telemetry policy behavior.
 	Telemetry policy.TelemetryOptions
-	// PerCallOptions are options to run on every request
-	PerCallOptions []policy.Policy
+
+	// PerCallPolicies are options to run on every request
```
Comment (JeffreyRichter) [inline sdk/data/aztables/zc_client_options.go:21]:
```suggestion
	// PerCallPolicies are policies that execute once per operation
```

File: sdk/data/aztables/zc_client_options.go [hunk 2]
```diff
@@ -11,12 +11,18 @@ import (
...
+	PerCallPolicies []policy.Policy
+
+	// PerTryPolicies are options to run on every retry
```
Comment (JeffreyRichter) [inline sdk/data/aztables/zc_client_options.go:24]:
```suggestion
	// PerTryPolicies are policies that execute once per retry of an operation
```

**Review by JeffreyRichter — APPROVED** [review]
