### PR TITLE
[azeventhubs+azservicebus] Updating our user agent format so it matches HTTP

### LINKED ISSUE #19673: [azeventhubs/azservicebus] User agent strings are missing runtime information and have an incorrect leading slash
The user agent strings for azeventhubs and azservicebus are formatted incorrectly or missing information. The HTTP SDK's headers look like this:

HTTP:
```
User-Agent: azsdk-go-azidentity/v1.2.0 (go1.19.3; linux)
User-Agent: azsdk-go-azsecrets/v0.11.0 (go1.19.3; linux)
```

And SB and EH:
```
USER AGENT: /azsdk-go-azservicebus/v1.1.4
```
We need to add in the OS section, and _remove_ the leading '/' (no other SDKs appear to have it).

### PR DESCRIPTION
**Pull request by richardpark-msft**
User-Agent was formatted inconsistent with our HTTP-based clients which was making doing simple reporting difficult. 

This brings it inline with what we do for user agents in HTTP, including when a client specified appid is present.

Examples:
* No appID: `azsdk-go-azeventhubs/v0.3.1 (go1.19.3; linux)`
* With AppID: `userApplicationID azsdk-go-azeventhubs/v0.3.1 (go1.19.3; linux)`

Fixes #19673

### CODE REVIEW

File: sdk/messaging/azeventhubs/internal/namespace.go [hunk 1]
```diff
@@ -457,7 +456,7 @@ func (ns *Namespace) GetEntityAudience(entityPath string) string {
 func (ns *Namespace) getUserAgent() string {
 	userAgent := rootUserAgent
 	if ns.userAgent != "" {
```
Comment (jhendrixMSFT) [inline sdk/messaging/azeventhubs/internal/namespace.go:458]: So `ns.userAgent` is the user-provided application ID?

Comment (richardpark-msft) [reply sdk/messaging/azeventhubs/internal/namespace.go:458]: Yeah, I never changed the internal field name but it maps from this exposed option: 
* (option) https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/consumer_client.go#L46
* (copying) https://github.com/Azure/azure-sdk-for-go/blob/1ad22a964ea16c159e7e3f28263c940667d61519/sdk/messaging/azeventhubs/consumer_client.go#L249

**Review by jhendrixMSFT — APPROVED** [review]
