### PR TITLE
Fix #20718

### LINKED ISSUE #20718: NewClientFromConnectionString doesn't support SAS tokens with custom endpoints
### Bug Report

- SDK: `github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.0.0 h1:u/LLAOFgsMv7HmNL4Qufg58y+qElGOt5qv0z1mURkRY=`
- `go version go1.20.2 darwin/amd64`

### Reproduction Steps

1. Start Azurite
2. Create a SAS token (example below uses the default Azurite access key)
3. Try to create a client with NewClientFromConnectionString:

```go
connectionString := "AccountName=devstoreaccount1;SharedAccessSignature=sig=PTTuImbY50brWEx%2FEBwY9czhUpSYzi5IGVg6utbiD2A%3D&sp=raw&sr=c&sv=2020-02-10;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
containerName := "89d52d33-166d-4e69-8c0b-39e5c1e7940f"
client, err := azblob.NewClientFromConnectionString(connectionString, nil)
content := []byte("hello")
_, err = client.UploadBuffer(context.TODO(), containerName, "test.txt", content, nil)
```

### Expected

Client uploads a file to `http://127.0.0.1:10000/devstoreaccount1/89d52d33-166d-4e69-8c0b-39e5c1e7940f/test.txt`

### Actual

Client errors, as the upload was attempted to `https://devstoreaccount1.blob.core.windows.net/89d52d33-166d-4e69-8c0b-39e5c1e7940f/test.txt`

### PR DESCRIPTION
**Pull request by jlaundry**
As per #20718, this fixes support for Blob and Queue's NewClientFromConnectionString where the connection string uses both a SAS token and (Blob|Queue)Endpoint parameters.

I've also created `azqueue/internal/shared/shared_test.go`, using the azblob equivalent as a baseline

### CODE REVIEW

File: sdk/storage/azblob/internal/shared/shared.go [hunk 1]
```diff
@@ -98,9 +98,18 @@ func ParseConnectionString(connectionString string) (ParsedConnectionString, err
 		if !ok {
 			return ParsedConnectionString{}, errors.New("connection string missing AccountKey and SharedAccessSignature")
 		}
-		return ParsedConnectionString{
-			ServiceURL: fmt.Sprintf("%v://%v.blob.%v/?%v", defaultScheme, accountName, defaultSuffix, sharedAccessSignature),
-		}, nil
+
+		blobEndpoint, ok := connStrMap["BlobEndpoint"]
```
Comment (souravgupta-msft) [inline sdk/storage/azblob/internal/shared/shared.go:102]: I created the connection string from SAS using the portal. Its format is like this,

`BlobEndpoint=https://xxxxxxxx.blob.core.windows.net/;QueueEndpoint=https://xxxxxxxxx.queue.core.windows.net/;FileEndpoint=https://xxxxxxxx.file.core.windows.net/;TableEndpoint=https://xxxxxxxx.table.core.windows.net/;SharedAccessSignature=xxxxxxxxxxxxxxxx`

There is no `AccountName` here. So, the above code for checking account name also needs a fix.
```
accountName, ok := connStrMap["AccountName"]
if !ok {
	return ParsedConnectionString{}, errors.New("connection string missing AccountName")
}
```

Comment (souravgupta-msft) [reply sdk/storage/azblob/internal/shared/shared.go:102]: If you want, we can update this logic and fix this in some other PR.
I have done a similar fix in `azfile` package.
https://github.com/Azure/azure-sdk-for-go/pull/20798

Comment (jlaundry) [reply sdk/storage/azblob/internal/shared/shared.go]: Hi @souravgupta-msft, you're right.

I've added further tests, and then refactored the ParseConnectionString because the logic was too confusing and duplicated.

Comment (jlaundry) [reply sdk/storage/azblob/internal/shared/shared.go]: Resolving thread as code is now outdated

**Review by siminsavani-msft — APPROVED** [review]
Thank you for your contribution!

**Review by tasherif-msft — APPROVED** [review]

**Comment by jlaundry** [comment]
Hey @siminsavani-msft @tasherif-msft - is there anything left to do before this can be merged?

File: sdk/storage/azblob/internal/shared/shared.go [hunk 2]
```diff
@@ -113,19 +97,35 @@ func ParseConnectionString(connectionString string) (ParsedConnectionString, err
...
+	if has_accountName && has_accountKey {
 		return ParsedConnectionString{
-			ServiceURL:  blobEndpoint,
+			ServiceURL:  serviceURL,
 			AccountName: accountName,
 			AccountKey:  accountKey,
 		}, nil
+	} else if has_sharedAccessSignature {
+		return ParsedConnectionString{
+			ServiceURL: fmt.Sprintf("%v/?%v", serviceURL, sharedAccessSignature),
```
Comment (souravgupta-msft) [inline sdk/storage/azblob/internal/shared/shared.go:123]: Can you add a check above the return statement for checking whether the serviceURL has trailing slash. If not, then add it and update this statement.
```suggestion
			ServiceURL: fmt.Sprintf("%v?%v", serviceURL, sharedAccessSignature),
```

File: sdk/storage/azqueue/internal/shared/shared.go [hunk 3]
```diff
@@ -104,19 +88,34 @@ func ParseConnectionString(connectionString string) (ParsedConnectionString, err
...
+	if has_accountName && has_accountKey {
 		return ParsedConnectionString{
-			ServiceURL:  queueEndpoint,
+			ServiceURL:  serviceURL,
 			AccountName: accountName,
 			AccountKey:  accountKey,
 		}, nil
+	} else if has_sharedAccessSignature {
+		return ParsedConnectionString{
+			ServiceURL: fmt.Sprintf("%v/?%v", serviceURL, sharedAccessSignature),
```
Comment (souravgupta-msft) [inline sdk/storage/azqueue/internal/shared/shared.go:114]: Same as previous. Please make these two changes. Everything else looks good.

File: sdk/storage/azblob/internal/shared/shared.go (hunk 2 above)
Comment (jlaundry) [reply sdk/storage/azblob/internal/shared/shared.go]: Done - had to modify test data to do this though...

File: sdk/storage/azqueue/internal/shared/shared.go (hunk 3 above)
Comment (jlaundry) [reply sdk/storage/azqueue/internal/shared/shared.go]: Done, same

**Review by souravgupta-msft — APPROVED** [review]

File: sdk/storage/azblob/internal/shared/shared.go [hunk 4]
```diff
@@ -113,19 +97,40 @@ func ParseConnectionString(connectionString string) (ParsedConnectionString, err
...
 
-	if blobEndpoint, ok := connStrMap["BlobEndpoint"]; ok {
+	blobEndpoint, has_blobEndpoint := connStrMap["BlobEndpoint"]
+	accountName, has_accountName := connStrMap["AccountName"]
+
+	var serviceURL string
+	if has_blobEndpoint {
+		serviceURL = blobEndpoint
+	} else if has_accountName {
+		serviceURL = fmt.Sprintf("%v://%v.blob.%v/", protocol, accountName, suffix)
```
[the remark this answers is not in the document]
Comment (jlaundry) [reply sdk/storage/azblob/internal/shared/shared.go:107]: I don't think so: appending a trailing / only happens after serviceURL is set, and only if !strings.HasSuffix(serviceURL, "/")...

Can you please share the failed test data, or share a unit test that recreates the issue?

[the remark this answers is not in the document]
Comment (jlaundry) [reply sdk/storage/azblob/internal/shared/shared.go:107]: Alternatively, we could go back to not appending a trailing /, which as far as I can tell, has no material impact?

[the remark this answers is not in the document]
Comment (souravgupta-msft) [reply sdk/storage/azblob/internal/shared/shared.go:107]: If the `suffix` in the above suggested change is **core.windows.net/** (having trailing slash), then the current code which is,
`serviceURL = fmt.Sprintf("%v://%v.blob.%v/", protocol, accountName, suffix)`
will create, `serviceURL="https://accountName.blob.core.windows.net//"` (two slashes at the end).

So, the trailing slash while creating the serviceURL can be removed as suggested in the change above.
Lines 112-114 anyways takes care of checking and adding the trailing slash.

[the remark this answers is not in the document]
Comment (jlaundry) [reply sdk/storage/azblob/internal/shared/shared.go]: Ahhhh, ok I understand now. Done, and added further unit tests.

**Review by siminsavani-msft — APPROVED** [review]
