### PR TITLE
[azservicebus] Fixing the issue with 404's failing fast-ish, but not fast.

### LINKED ISSUE #16088: [azservicebus] amqp-common's link.RetryableRPC() retries an entity does not exist
This can lead to a series of retries that will not work. It'd be nice to be able to pass in an error handling strategy per RPC call so we can provide better error handling when we know what the context of the call is and just fail early.

The underlying error is:

Code: 404
Description: "The messaging entity 'sb://<mysb>.servicebus.windows.net/samples' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:888b355f-038e-42e1-ab5d-cf1d0bfa20d1_G53, SystemTracker:riparkdev2.servicebus.windows.net:samples, Timestamp:2021-11-04T17:42:29"

### PR DESCRIPTION
**Pull request by richardpark-msft**
The main issue is that the negotiateClaim() function was doing it's own
retries and it wasn't properly handling 404 as a "fatal" error. We'd eliminated
the outmost retry set (where we were basically doing 'n' retries around 'n' retries)
but there were still some incorrect retries happening in the negotiateClaim 
function itself.

Rather than continuing to patch the 'internal' version I'm just moving it
all into the azservicebus package and leveraging the normal retry and error 
recovery. I stopped short of doing a full change (to make it so we can hold 
onto an RPC link for claims negotiation).

Some supporting changes:
- mgmtError is now rpcError and is just generically the "request/response"
  error type. Also, the actual decision of creating an rpcError is built
  in to rpcLink.RPC(), rather than being done by callers.
- Small change to make NewRPCLink take an args structure and remove the
  options that weren't used.
- Removed 'tab' calls in code I'm modifying since we're going to be
  replacing them/moving them anyways.

Fixes #16088 (completely this time)

### CODE REVIEW

File: sdk/messaging/azservicebus/internal/errors.go [hunk 1]
```diff
@@ -171,10 +171,14 @@ func GetRecoveryKind(err error) recoveryKind {
...
 
-	var me mgmtError
+	var rpcErr rpcError
 
-	if errors.As(err, &me) {
-		code := me.RPCCode()
+	if errors.As(err, &rpcErr) {
+		code := rpcErr.RPCCode()
+
+		if code == 404 {
```
Comment (jhendrixMSFT) [inline sdk/messaging/azservicebus/internal/errors.go:179]: At some point would be good to switch to using the constants from the [`net/http`](https://pkg.go.dev/net/http#pkg-constants) package.

File: sdk/messaging/internal/cbs/cbs.go [hunk 2]
```diff
@@ -1,90 +0,0 @@
-// Package cbs provides the functionality for negotiating claims-based security over AMQP for use in Azure Service Bus
```
Comment (jhendrixMSFT) [inline sdk/messaging/internal/cbs/cbs.go:1]: What will this mean for Event Hubs?

Comment (richardpark-msft) [reply sdk/messaging/internal/cbs/cbs.go:1]: When we get there I'll merge whatever we end up with back into internal.

Comment (richardpark-msft) [reply sdk/messaging/internal/cbs/cbs.go:1]: (I have some more changes coming for this but I didn't want to do it all in the same PR)

File: sdk/messaging/azservicebus/internal/errors.go (hunk 1 above)
Comment (richardpark-msft) [reply sdk/messaging/azservicebus/internal/errors.go:179]: They do seem to line up with HTTP status codes but they aren't coming back from HTTP in this case. 

I could make some aliases though since it's kind of silly to just have the values hanging out.

Comment (richardpark-msft) [reply sdk/messaging/azservicebus/internal/errors.go:179]: (going to leave this for now. I need to go actually repro some of these to see the descriptions that come back from the service)
